project:
  type: website

website:
  title: "quarto-test"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: simplex
    css: styles.css
    
comments:
  giscus:
    repo: sandra-jurela/quarto-test

editor: visual

