project:
  type: website

website:
  title: "Sandra Jurela"
  site-url: https://sjurela.netlify.app
  description: "This is Sandra Jurela's personal Blog."
  navbar:
    logo: img/logo.png
    href: index.html
    right:
      - text: Home
        href: index.qmd 
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/sandra-jurela
      - icon: linkedin
        href: https://www.linkedin.com/in/sandra-jurela-a95985211/
      - icon: rss
        href: index.xml
  google-analytics: "G-MJRRNS5NVY"
  cookie-consent: false
  
format:
  html:
    theme: theme-light.scss
    css: styles.css
      # light: [litera, theme-light.scss]  #- spacelab #theme.scss  #theme: cosmo
      # dark: [litera, theme-dark.scss] #- theme.scss #css: styles.css

editor: visual

